//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Person()
        {
            this.T_Operation = new HashSet<T_Operation>();
        }
    
        public int personId { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string otherName { get; set; }
        public int nationalityFk { get; set; }
        public System.DateTime birthday { get; set; }
        public string commentPerson { get; set; }
        public string road { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string job { get; set; }
        public string documentType { get; set; }
        public System.DateTime idValidity { get; set; }
        public string docNumber { get; set; }
    
        public virtual T_Nationality T_Nationality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Operation> T_Operation { get; set; }
    }
}
